name: Continuous Integration

on:
	push:
	paths:
		- 'src/**'
		- '.github/workflows/**'
	pull_request:
	paths:
		- 'src/**'
		- '.github/workflows/**'
jobs:
	merge:
		name: Make
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2
			- name: Make script
				run: make
			- uses: actions/upload-artifact@v2
				with:
					name: script
					path: ./to_arch
				if-no-files-found: error
